# Generated by Django 3.1 on 2020-08-09 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_user_lastname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dateOfBirth',
            new_name='dateofbirth',
        ),
    ]
