# Generated by Django 3.1 on 2020-08-09 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20200809_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uniqueId',
            new_name='uniqueid',
        ),
    ]
