# Generated by Django 3.1 on 2020-08-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20200809_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uniqueid',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
