# Generated by Django 3.1 on 2020-08-11 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='description',
        ),
    ]
